### ISSUE TITLE
How to build a WHERE IN property query

### ISSUE THREAD

**Issue by transistive** [WikibaseSolutions/php-cypher-dsl#1]
Hello!

I am starting to your DSL in some of my projects and I love it! I am stuck however how to build a query like this:

```CYPHER
MATCH (x:Node) WHERE x.id IN $ids RETURN x
```

I am stuck here:

```php
Query::new()->match(Query::node('Node')->named('x'))
            ->where(Query::variable('x.id')-> STUCK HERE )
            ->toQuery()
```

Ideally, I would love to be able to do something like this:

```php
Query::new()->match(Query::node('Node')->named('x'))
            ->where(Query::variable('x')->property('id')->in(Query::param('ids')))
            ->returning(Query::variable('x'))
            ->toQuery()
```

Is this already possible? I can't find it.

Thanks in advance!

- Ghlen

**Comment by 26** [comment]
I have added this feature in v2.5.0 (4aa5ab2f396c43bac4ba075636cde44fd505bc6b).

**Comment by transistive** [comment]
Super! Thank you very much :+1:  Great work
