### ISSUE TITLE
Add "NOT" clause

### ISSUE THREAD

**Issue by wgevaert** [WikibaseSolutions/php-cypher-dsl#2]
Hello!

I am trying to write a query of the following form (with some extra conditions):

```
MATCH (n)<-(m) WHERE NOT EXISTS { MATCH (m)<-() } DELETE m;
```

How do I do this nicely using this package?

Using the raw clause, I have done it like so:

```
$innerQuery = Query::new()->match(Query::node()->named($m)->relationshipFrom(Query::node()));
$query = Query::new()->match(
    Query::node()->named($n)->relationshipFrom(Query::node()->named($m))
)->raw(
    'NOT EXISTS {',
    $innerQuery->build() . '}'
)->delete(
    $m
)->build();
```

But the `. '}'` at the end of the raw clause seems a bit awkward to me. Would it be possible to either:
- Implement a BooleanType clause `notClause` that accepts any BooleanType.
- Implement a method `Query::notExists` with the same input & output as `Query::exists` (possibly just a wrapper of `Query::exists` in a `notClause`)

Cheers!
wgevaert

**Comment by wgevaert** [comment]
hmmm, maybe `rawExpression` instead of `raw` would've been more appropriate.

**Comment by 26** [comment]
`NOT` is not actually a clause, but an operator in Cypher. I will implement it as so.
