### ISSUE TITLE
Add subqueries and UNIONS

### ISSUE THREAD

**Issue by transistive** [WikibaseSolutions/php-cypher-dsl#28]
Hello,

I would love to see support for [subqueries and unions](https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/)

It will make it trivial to combine multiple queries.

Right now, I was thinking about the `Query` class. It should just need to have two extra methods: `call`/`subQuery` and `union`

Both methods should expect the `Query` class as their only parameter. This way  we can simply combine queries and add them as subqueries.

What do you think?

Kind regards,

Ghlen

**Comment by marijnvanwezel** [comment]
Sounds good. I'll work on it as soon as possible.
