### ISSUE TITLE
Use nanoseconds without milli- or microseconds

### ISSUE THREAD

**Issue by wgevaert** [WikibaseSolutions/php-cypher-dsl#34]
This package blocks me when I try to make a temporal value by providing hour, minute, second and nanoseconds, but this should be possible.

I think I will make a PR to solve this shortly.

**Comment by wgevaert** [comment]
I made a [pull request](https://github.com/WikibaseSolutions/php-cypher-dsl/pull/35)

**Comment by marijnvanwezel** [comment]
Closed by #35.
